module.exports = {
    auth: require('./auth'),
    user: require('./user'),
    mgmt: require('./mgmt'),
    comments: require('./comments'),
    images: require('./images'),
    invites: require('./invites'),
    notifications: require('./notifications'),
    agencies: require('./agencies'),
    threads: require('./threads'),
    tours: require('./tours'),
    tourdates: require('./tourdates'),
    todos: require('./todos'),
    venues: require('./venues'),
    merch: require('./merch'),
}